-- AlterTable
ALTER TABLE "files" ADD COLUMN "isHF" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "settings" ADD COLUMN "useHFStorage" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "settings" ADD COLUMN "HFToken" TEXT NOT NULL DEFAULT '';
ALTER TABLE "settings" ADD COLUMN "HFBucket" TEXT NOT NULL DEFAULT '';